language: node_js
node_js:
- 8
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: S0QfDNeZGyd0r/yAVOe2lKyJv1o3py45n84SSVMzGmmXnr+HxGDSyhhpGjvGUKjZpr9nd52xDIVV2zBXJcOUH8cHdGQ6dAlyMmONsQ8J3ru88uBmiKvmf7IPAem/Xx6lw3cdYViy6WXE1PUt5NmJHYkn6P4p3SaRc56reB3zDBNUiUFM4r4FGbhgE/RVfD+KooNeAdYE8R+gjHuXPlpZ2Rn0BZ3FrIZNs+vFIE4uIKh8h/VCv9mxZhLk3znmVksJpBr1ZRwVll1/tuytbYxrzHLChHXUmvzx78REyARx9P5hQQVihpn/aWwsIBtpdaQTQmSNFt97rh+MouKjScv2U2/+JtgnbkOcaxur0daEsaTUiu7sNbRv9f5Rg1jBAleqF3tAnHpkfAVlsRNUrjk/lnFGc6yfef1ycwQZnNVR25+1MY+GlNRNZ8wnGVAF9hMBqy6qnlmnva6mOPrm2mLe/rZXOGDxRqA7iftrywIIXmdrNbzR+vj49El0Xcdf39vnStmmTMYDuCQ024tASbGafqYbDVc4IWdKQ2TBaaDlHq46qFj3DGttGiZiwk14La2BagP6IyGVFrFGHRkHd1rGG8GzSF7rYH0ZAxZcVPIcEHSxGdU465jmU7QdOyrDWiUbth8CEkaiK0ucg880eqEgd81FpZZjGhZmTzpUvS832wo=
